package br.maua.Enum;

public enum Armadura {
    CAPA_DE_COURO, CAPA_DA_INVISIBILIDADE, CAPA_CELESTIAL, ARMADURA_PESADA_DE_COBRE ,
    ARMADURA_PESADA_DE_OURO, ARMADURA_PESADA_DE_DIAMANTE,ARMADURA_PESADA_CELESTIAL, ARMADURA_DE_COBRE, ARMADURA_DE_FERRO,
    ARMADURA_DE_DIAMANTE, ARMADURA_CELESTIAL, ROUPA_DE_VELOCIDADE, NAO_POSSUI
}
